# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - performancecheck

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerkartik.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b3fd6919e4ac42f9bbc2bb2d0b12c83d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cbecbd589c384e9486b2b8f7f368a148 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerkartik.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b3fd6919e4ac42f9bbc2bb2d0b12c83d }}/perfomace:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'performancecheck'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0bf21aaef9184545b56c75eade0c75c3 }}
        images: 'testdockerkartik.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b3fd6919e4ac42f9bbc2bb2d0b12c83d }}/perfomace:${{ github.sha }}'